from cmdapp.parser import TableMeta

TABLE_ACCOUNT = TableMeta(name='account', singular='account', plural='accounts', columns={'id': {'dtype': 'int'}, 'name': {'flags': [], 'comment': 'unique name for reference', 'dtype': 'str', 'required': True}, 'description': {'flags': ['i', 'bio'], 'comment': 'bio information', 'dtype': 'str', 'proc': 'telex'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(name)'])

TABLE_WALLET = TableMeta(name='wallet', singular='wallet', plural='wallets', columns={'id': {'dtype': 'int'}, 'name': {'flags': [], 'comment': 'unique name for reference', 'dtype': 'str', 'required': True}, 'account': {'flags': ['a'], 'comment': 'owned account', 'metavar': 'account_id', 'dtype': 'int', 'required': True}, 'description': {'flags': ['i'], 'comment': "detail information for the wallet like account's id, bank's name,...", 'dtype': 'str', 'proc': 'telex'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(name)'])

TABLE_LIQUIDITY = TableMeta(name='liquidity', singular='liquidity', plural='liquidities', columns={'id': {'dtype': 'int'}, 'wallet': {'flags': ['w'], 'comment': 'wallet', 'metavar': 'wallet_id', 'dtype': 'int', 'required': True}, 'currency': {'comment': 'currency unit', 'dtype': 'str', 'required': True}, 'balance': {'flags': ['v', 'value'], 'comment': 'balance (amount of money)', 'dtype': 'float', 'required': True}, 'calculate': {'comment': 'calculated balance based on saved transactions', 'dtype': 'float'}, 'timestamp': {'flags': ['t', 'at'], 'comment': 'timestamp to summarize', 'dtype': 'datetime', 'required': True}, 'created_at': {'dtype': 'datetime', 'required': True}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'deleted_at'], constraints=[])

TABLE_TAG = TableMeta(name='tag', singular='tag', plural='tags', columns={'id': {'dtype': 'int'}, 'name': {'flags': [], 'comment': 'unique name for reference', 'dtype': 'str', 'required': True}, 'description': {'flags': ['i'], 'comment': 'describe the context to use it', 'dtype': 'str', 'proc': 'telex'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(name)'])

TABLE_TRANSACTION = TableMeta(name='tx', singular='transaction', plural='transactions', columns={'id': {'dtype': 'int'}, 'amount': {'flags': [], 'comment': 'transaction value (amount of money)', 'dtype': 'float', 'required': True}, 'currency': {'flags': ['u'], 'comment': 'currency unit', 'dtype': 'str', 'required': True}, 'message': {'flags': ['m'], 'comment': 'describe the context of the transaction', 'dtype': 'str', 'proc': 'telex', 'required': True}, 'payer': {'flags': ['p'], 'comment': 'wallet used to pay', 'metavar': 'wallet_id', 'dtype': 'int'}, 'receiver': {'flags': ['r'], 'comment': 'wallet that receive', 'metavar': 'wallet_id', 'dtype': 'int'}, 'category': {'flags': ['t'], 'comment': 'assign category for statistics', 'metavar': 'tag_id', 'dtype': 'int'}, 'timestamp': {'flags': ['at'], 'comment': 'happen time, recommended for statistics', 'metavar': 'timestamp', 'dtype': 'datetime'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=[])

TABLE_REPORT = TableMeta(name='report', singular='report', plural='reports', columns={'id': {'dtype': 'int'}, 'name': {'flags': ['n'], 'comment': 'name for reference', 'dtype': 'str', 'proc': 'telex', 'required': True}, 'filters': {'comment': 'filters apply on transactions', 'dtype': 'json'}, 'txs': {'comment': 'transactions belongs to this report', 'metavar': 'transaction_ids', 'dtype': 'array', 'proc': 'int', 'required': True}, 'data': {'comment': 'report data', 'dtype': 'json'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'deleted_at'], constraints=['UNIQUE(name)'])

TABLE_ORDER = TableMeta(name='shopping', singular='order', plural='orders', columns={'id': {'dtype': 'int'}, 'tx': {'comment': 'paying transaction', 'metavar': 'transaction_id', 'dtype': 'int', 'required': True}, 'items': {'flags': ['p'], 'comment': 'buy products', 'dtype': 'array', 'proc': 'telex', 'required': True}, 'shop': {'comment': 'name of the shop', 'dtype': 'str', 'proc': 'telex'}, 'platform': {'comment': 'name of selling platform, like shopee, tiki,...', 'dtype': 'str', 'proc': 'telex'}, 'review': {'comment': 'review for received products', 'dtype': 'str', 'proc': 'telex'}, 'tag': {'comment': 'tag for filtering', 'metavar': 'tag_id', 'dtype': 'int', 'required': True}, 'complete': {'comment': 'received date', 'dtype': 'datetime'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(tx)'])

TABLE_SHARING = TableMeta(name='sharing', singular='sharing', plural='sharings', columns={'id': {'dtype': 'int'}, 'tx': {'comment': 'paying transaction', 'metavar': 'transaction_id', 'dtype': 'int', 'required': True}, 'people': {'comment': 'people sharing the expense', 'metavar': 'account_ids', 'dtype': 'array', 'proc': 'int', 'required': True}, 'shares': {'comment': 'the proportion of the expense that each person should pays. By default (set null), everyone splits the expense equally', 'dtype': 'array', 'proc': 'float'}, 'tag': {'comment': 'tag for filtering', 'metavar': 'tag_id', 'dtype': 'int'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(tx)'])

TABLE_EVENT = TableMeta(name='event', singular='event', plural='events', columns={'id': {'dtype': 'int'}, 'name': {'flags': ['n'], 'comment': 'name for reference', 'dtype': 'str', 'proc': 'telex', 'required': True}, 'tag': {'flags': ['t'], 'comment': 'tag that represent an event, used to filter sharing transactions', 'metavar': 'tag_id', 'dtype': 'int', 'required': True}, 'bills': {'comment': 'how much each person joining the event paid, received and needs to paided', 'dtype': 'array', 'proc': 'json', 'required': True}, 'sharings': {'comment': 'sharings belong to this event', 'dtype': 'array', 'proc': 'int', 'required': True}, 'currency': {'flags': ['c'], 'comment': 'chosen currency for the calculation', 'dtype': 'str', 'required': True}, 'rates': {'flags': ['r'], 'comment': 'exchange rates from other currencies to chosen currency', 'dtype': 'json'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(name)'])

TABLE_RESOURCE = TableMeta(name='resource', singular='resource', plural='resources', columns={'id': {'dtype': 'int'}, 'name': {'flags': [], 'comment': 'unique name for reference', 'dtype': 'str', 'required': True}, 'link': {'flags': ['l', 'url'], 'comment': 'link to fetch new notes', 'dtype': 'str', 'required': True}, 'option': {'flags': ['c', 'config'], 'comment': "options to parse notes like note format, scale level, default values for missing fields: `{'format': '.csv', 'scale': 1000, 'payer': 'me'}`", 'dtype': 'json', 'proc': 'str'}, 'scope': {'flags': ['t', 'type'], 'comment': 'what data is inside each note: pure transaction, sharing or order', 'dtype': 'str', 'choices': ['tx', 'order', 'sharing'], 'default_value': 'tx'}, 'last_import': {'comment': 'last imported timestamp', 'dtype': 'datetime'}, 'last_record': {'comment': 'last record from last importing, used to find new notes for next importing', 'dtype': 'json'}, 'created_at': {'dtype': 'datetime', 'required': True}, 'updated_at': {'dtype': 'datetime'}, 'deleted_at': {'dtype': 'datetime'}}, meta_columns=['id', 'created_at', 'updated_at', 'deleted_at'], constraints=['UNIQUE(name)'])

DATABASE_SCHEMA = [TABLE_ACCOUNT, TABLE_WALLET, TABLE_LIQUIDITY, TABLE_TAG, TABLE_TRANSACTION, TABLE_REPORT, TABLE_ORDER, TABLE_SHARING, TABLE_EVENT, TABLE_RESOURCE]
