SCOPE_TX = "tx"
SCOPE_ORDER = "order"
SCOPE_SHARING = "sharing"
IMPORT_SCOPES = [SCOPE_TX, SCOPE_ORDER, SCOPE_SHARING]

SHARE_NOTE_PATTERN = r"(\w+)\s*(?:[:=]([\d\.]+))?"

CONVERSION_RATE_PATTERN = r"^\s*(\w+)\s*[=:]\s*([\d\.]+)\s*$"

BILL_PERSON = "individual"
BILL_PAID = "paid"
BILL_RECEIVED = "received"
BILL_NEEDS = "needs"
BILL_REFUND = "refund"
BILL_TRANSFER_FROM = "from"
BILL_TRANSFER_TO = "to"
BILL_TRANSFER_AMOUNT = "amount"

ANONYMOUS_NAME = "???"

REPORT_IN = "in"
REPORT_OUT = "out"

CONFIG_NOTE_FIELDNAMES = "NOTE"
CONFIG_REPORT_FIELDNAMES = "REPORT"
CONFIG_EVENT_FIELDNAMES = "EVENT"

ENV_DATABASE_PATH = "MONEY_DATABASE_PATH"
ENV_CONFIG_PATH = "MONEY_CONFIG_PATH"
